// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSPG96S7SyUFnvNKVwBtcvAVDXrj8Fso',
    appId: '1:889888199226:web:ac3df298e7318853cfdb03',
    messagingSenderId: '889888199226',
    projectId: 'notes-7efc8',
    authDomain: 'notes-7efc8.firebaseapp.com',
    storageBucket: 'notes-7efc8.firebasestorage.app',
    measurementId: 'G-SL9PXSHC37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYcNFz9CxuUZqMzKaDYAk-sCKUEDVvRk',
    appId: '1:889888199226:android:a59f71e68afe66f5cfdb03',
    messagingSenderId: '889888199226',
    projectId: 'notes-7efc8',
    storageBucket: 'notes-7efc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJutNznoEDcAn0HxRKoWi9ZCjRiayDHIQ',
    appId: '1:889888199226:ios:fd34c72c9c8406e3cfdb03',
    messagingSenderId: '889888199226',
    projectId: 'notes-7efc8',
    storageBucket: 'notes-7efc8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJutNznoEDcAn0HxRKoWi9ZCjRiayDHIQ',
    appId: '1:889888199226:ios:fd34c72c9c8406e3cfdb03',
    messagingSenderId: '889888199226',
    projectId: 'notes-7efc8',
    storageBucket: 'notes-7efc8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsSPG96S7SyUFnvNKVwBtcvAVDXrj8Fso',
    appId: '1:889888199226:web:3e5f66d487eaf330cfdb03',
    messagingSenderId: '889888199226',
    projectId: 'notes-7efc8',
    authDomain: 'notes-7efc8.firebaseapp.com',
    storageBucket: 'notes-7efc8.firebasestorage.app',
    measurementId: 'G-RJJ8779QGG',
  );
}
